<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Product>ONIDenseLogic</Product>
    <AssemblyTitle>Automation Expanded</AssemblyTitle>
    <Authors>Dense Logic Team</Authors>
    <Copyright>Copyright ©Dense Logic Team 2026</Copyright>
    <FileVersion>2.7.0.0</FileVersion>
    <RootNamespace>ONI_DenseLogic</RootNamespace>
    <Description>Dense Logic Gates and more for Oxygen Not Included</Description>
    <AssemblyVersion>2.3.0.0</AssemblyVersion>
    <CopyPreview>false</CopyPreview>
    <LastWorkingBuild>719533</LastWorkingBuild>
    <Platforms>Mergedown</Platforms>
  </PropertyGroup>
</Project>
